export const turkishGirlNames = [
  "Aylin",
  "Elif",
  "Zeynep",
  "Ceren",
  "Melis",
  "Selma",
  "Ebru",
  "Esra",
  "Gizem",
  "Hale",
  "Merve",
  "Duygu",
  "Ezgi",
  "İrem",
  "Damla",
  "Zara",
  "Aslı",
  "Begüm",
  "Nazlı",
  "Elanur",
  "Buse",
  "İpek",
  "Selin",
  "İlayda",
  "Ela",
  "Leyla",
  "Emine",
  "Cemre",
  "Yasmin",
  "Nisa",
  "Lina",
  "Yaren",
  "Belgin",
  "Nisan",
  "Lara",
  "Ada",
  "Cansu",
  "İnci",
  "Esen",
  "Mira",
  "Gül",
  "Alara",
  "Sude",
  "Zümra",
  "Rabia",
  "Serra",
  "Esen",
  "Alina",
  "Serra",
  "Efsa",
  "Büşra",
  "Hira",
  "Ezgi",
  "Leman",
  "İclal",
  "Sima",
];

export const hobbiesList = [
  "camping",
  "watchingMovies",
  "readingBooks",
  "cooking",
  "traveling",
  "listeningToMusic",
  "playingFootball",
  "photography",
  "dancing",
  "doingYoga",
  "fishing",
  "swimming",
  "mountainClimbing",
  "surfing",
  "biking",
  "running",
  "painting",
  "pottery",
  "playingBasketball",
  "playingVolleyball",
  "playingTennis",
  "acting",
  "playingInstrument",
  "gardening",
  "diving",
  "skiing",
  "playingBilliards",
  "playingChess",
  "playingVideoGames",
  "freeDiving",
];


export const turkishGirlBios = [
  "Müzik tutkunu",
  "Yemeksever",
  "Spor yapmayı seven biri",
  "Dans etmeye bayılırım",
  "Kitap kurdu",
  "Hayvan dostu",
  "Sanatsever",
  "Macera arayan biri",
  "Kahve bağımlısı",
  "Rüyalarımı takip eden biriyim",
  "Güzel anılar biriktirmeyi seviyorum",
  "Doğayı keşfetmek istiyorum",
  "Kültürel etkinliklere ilgi duyarım",
  "Gülümsemeyi unutmam",
  "Teknoloji meraklısı",
  "Eğlenceli anlar yaşamayı seviyorum",
  "Sessiz anları da takdir ederim",
  "Arkadaşlarımı mutlu etmek benim için önemli",
  "Geleceğe umutla bakıyorum",
  "Hızlı arabalara bayılırım",
  "Sahilde yürümek beni rahatlatır",
  "Güzel bir sohbet her zaman iyidir",
  "Moda takipçisiyim",
  "Güzel yemekler denemek istiyorum",
  "Seyahat etmek hayalimdeki şey",
  "Mizah anlayışım çok iyidir",
  "Müzik dinlemek ruhumu dinlendirir",
  "Yıldızları izlemeyi seviyorum",
  "Güneşin tadını çıkarmayı unutmam",
  "Gece yürüyüşleri yapmayı seviyorum",
  "Sessiz bir kitap ve kahve mükemmeldir",
  "Düşündüren filmler beni etkiler",
  "Müzikle dans etmek ruhuma iyi gelir",
  "Hobilerim arasında resim yapmak da var",
  "Hayvan barınağına gönüllü olmak istiyorum",
  "Sosyal sorumluluk projelerine ilgi duyarım",
  "Doğa yürüyüşleri yapmayı seviyorum",
  "Bir gün dünya turuna çıkmak istiyorum",
  "Birlikte yeni yerler keşfetmek isteyen var mı?",
  "Sadece yaşamayı seviyorum",
  // Add more bios here...
];
export const turkishCities = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",
];